# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.0
  - 1.7
  - nightly
os:
  - linux
arch:
  - x64
  - x86
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: DocMeta, doctest
          using TropicalCyclonePotentialIntensity
          DocMeta.setdocmeta!(TropicalCyclonePotentialIntensity, :DocTestSetup, :(using TropicalCyclonePotentialIntensity); recursive=true)
          doctest(TropicalCyclonePotentialIntensity)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
